### ISSUE TITLE
Support "multi_license_permissive" attribute for xray license policies

### ISSUE THREAD

**Issue by long-lo** [jfrog/terraform-provider-xray#1]
**Describe the bug**
Current version of provider does not allow passing attribute 'multi_license_permssive' as documented in the xray v2 restful apis.

**Requirements for and issue**
- [x] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue)
```
resource "xray_policy" "lic_policy" {
  name = "lic_policy"
  description = "License policy"
  type = "license"

  rules {
    name = "lic_rule"
    criteria {
      banned_licenses = [
      ...
      ]
      multi_license_permissive = true
    }
    actions {
      ...
    }
  }
}

```
- [x] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
```
7.17.5
```
- [x] Your version of terraform
```
Terraform v.0.15.4
+ provider registry.terraform.io/jfrog/artifactory v2.3.1
```
**Expected behavior**
Provider should support latest restful APIs and attributes.  Allow to pass "multi_license_permissive" attribute for license xray policies.

**Additional context**
https://www.jfrog.com/confluence/display/JFROG/Xray+REST+API#XrayRESTAPI-CreatePolicy
License sample jfrog/terraform-provider-artifactory#3 
```
{
    “name”: “lic_policy”,
    “description”: “License policy”,
    “type”: “license”,
    “rules”: [
         {
            “name”: “lic_rule”,
            “criteria”: {
                “banned_licenses”: [
                    “Apache-1.0",
                    “Apache-2.0”
                ],
                “allow_unknown”: true,
                “multi_license_permissive”: true
            },
            “actions”: {
                 “webhooks”: [],
                 “block_download”: {
                     “active”: true
                     “unscanned”: true
                 },
                 “block_release_bundle_distribution”: true,
                 “fail_build”: true,
                 “custom_severity”: “high”
             },
             “priority”: 1
         }
    ]
}```

**Comment by danielmkn** [comment]
Released in v0.0.1
