### ISSUE TITLE
[Feature Request] Adding operational_risk as an assigned policy type for resource "xray_watch"

### ISSUE THREAD

**Issue by DzeCin** [jfrog/terraform-provider-xray#103]
Hi,

I noticed that assigned policy type for a xray_watch resource cannot be operational_risk in the code, could you please allow it ?

https://github.com/jfrog/terraform-provider-xray/blob/5703a8c5d54ef09a2c892bb638f8a8fafe673014/pkg/xray/resource_xray_watch.go#L166

**Comment by danielmkn** [comment]
Hi @DzeCin, thank you for the ticket, it's fixed in v1.9.10
