### ISSUE TITLE
Custom Licenses support

### ISSUE THREAD

**Issue by Chirag94** [jfrog/terraform-provider-xray#128]
**Is your feature request related to a problem? Please describe.**
It would be great if this supports custom licenses too! Right now If I pass any arbitrary value in a licensed type policy I can see that in the UI but its mere a reference and not an actual license.

**Describe the solution you'd like**
Either custom licenses should be configured just like Policies and watches 
OR
They get created when supplied under policy section and should be visible in compliance licenses.

**Describe alternatives you've considered**
I could not find any REST API for this, however the import/export API does take this in account.

**Additional context**

**Comment by danielmkn** [comment]
Hi @Chirag94! Unfortunately, there is no API support to implement this. Also, we don't consider using import system settings API for that.
