### ISSUE TITLE
Support for bin_managers (Indexed Resources)

### ISSUE THREAD

**Issue by Chirag94** [jfrog/terraform-provider-xray#129]
There are certain binary manager configurations related to indexing of a 

- Repo and a package type
- Builds

And there Rest API supports are existing. It would be great if the tf provider also support them
https://jfrog.com/help/r/jfrog-rest-apis/get-repos-indexing-configuration

**Comment by alexhung** [comment]
@Chirag94 How would you imagine this feature be applied to the provider? Do you have an example of potential HCL? Are you thinking that this will be a new resource?
