### ISSUE TITLE
Ignore Rules cant have policies and watches both

### ISSUE THREAD

**Issue by Chirag94** [jfrog/terraform-provider-xray#130]
Hey Team,
Right now the ignore rules can be applied on a specific watch and a specific policy. But seems the terraform validator while planning is validating for either of them. 
I get a conflict error for them when I supply both.

Re:https://github.com/jfrog/terraform-provider-xray/blob/master/pkg/xray/resource_xray_ignore_rule.go#L132C5-L132C18
Whats the purpose of these?

**Comment by danielmkn** [comment]
Hi @Chirag94! The purpose of the `ConflictsWith` property there is to limit the practitioner to use only one of the `"policies"` or `"watches"` attributes. 
Our understanding was you can't add both watches and policies to the ignore rule, but I've tested it and it works. We will remove these parameters.
Thanks for reporting the issue!

**Comment by danielmkn** [comment]
@Chirag94 the fix is released in v1.14.1
