### ISSUE TITLE
Allow disabling specific risks in `xray_operational_risk_policy`'s `rule.criteria.op_risk_custom` block

### ISSUE THREAD

**Issue by eval-on-point** [jfrog/terraform-provider-xray#138]
I want to create an `xray_operational_risk_policy` that does not check the `newer_versions_greater_than` condition. Removing the condition from my `rule.criteria.op_risk_custom` block seems to just default the condition check to its default value rather than disable the condition check.

For example:
```
resource "xray_operational_risk_policy" "min_risk" {
  name        = "example"
  type        = "operational_risk"
  project_key = "test-project"

  rule {
    name     = "high-op-risk-alert"
    priority = 1

    criteria {
      op_risk_custom {
        use_and_condition                  = true
        is_eol                             = false
        #newer_versions_greater_than        = false
        committers_less_than               = 1
        risk                               = "medium"
      }
    }

    actions {
      mails                              = ["example@example.invalid"]
      block_release_bundle_distribution  = false
      notify_watch_recipients            = true
      notify_deployer                    = false
      create_ticket_enabled              = false // set to true only if Jira integration is enabled
      build_failure_grace_period_in_days = 5     // use only if fail_build is enabled
      fail_build                         = true

      block_download {
        unscanned = false
        active    = false
      }
    }
  }
}
```
Creates a policy with rules that look like this:
![image](https://github.com/jfrog/terraform-provider-xray/assets/59654069/0c2f2b68-6383-4db4-a843-47be0aeab9a2)

I want to be able to define this resource such that the box to the left of "Number of releases since greater than" is unchecked.

**Comment by alexhung** [comment]
@eval-on-point This issue stems from the combination of:
1. The provider has a default value of 1 set for this attribute, and
2. shortcoming of Terraform SDK: https://discuss.hashicorp.com/t/is-it-possible-to-differentiate-between-a-zero-value-and-a-removed-property-in-the-terraform-provider-sdk/43131/2.

To fix this issue, this is what I'm changing for this resource:
- remove default values from these 5 attributes: `release_date_greater_than_months`, `newer_versions_greater_than`, `release_cadence_per_year_less_than`, `commits_less_than`, and `committers_less_than`.
- only include values for these attributes in the API request when there are values. Fortunately for us, `0` is not a valid values for these attributes.
