### ISSUE TITLE
Error: Invalid string date type 'all-releaseBundles' is missing

### ISSUE THREAD

**Issue by AdiUbarale** [jfrog/terraform-provider-xray#150]
Hello Team,
We have imported the one of the xray_watch to terraform using[ xray_watch](https://registry.terraform.io/providers/jfrog/xray/latest/docs/resources/watch) resource, while reapplying the xray_watches resource using 'terraform' it throughs below error. 
> Error: Invalid string 
> expected type to be one of [all-repos repository all-builds build project all-projects], got all-releaseBundles

![image](https://github.com/jfrog/terraform-provider-xray/assets/83457620/f6d75855-1953-4480-b314-a269ee560d9f)
> Snip of resource block 
![image](https://github.com/jfrog/terraform-provider-xray/assets/83457620/e1962764-bbde-43dc-a9b1-9421f1b62f01)

We believe that resource type 'releaseBundles' is missing [here](https://github.com/jfrog/terraform-provider-xray/blob/master/pkg/xray/resource_xray_watch.go#L53) is causing the error. Please have a look and any quick fix to this problem is highly appreciated.  

**Expected behavior**
Import the existing 'xray watches' using terraform xray provider, copy the configuration from terraform state, update watch_recipients details to configuration locally and re-apply the terraform without any error.

**Comment by alexhung** [comment]
@AdiUbarale Thanks for the report! We will add the support for release bundles soon.
