### ISSUE TITLE
Xray report resources don't support import

### ISSUE THREAD

**Issue by neatcoder** [jfrog/terraform-provider-xray#157]
**Describe the bug**
Xray report resources, namely, `xray_vulnerabilities_report`, `xray_violations_report`, `xray_licenses_report`, don't support import opposed to the documentation that claims otherwise.
- [xray_vulnerabilities_report](https://registry.terraform.io/providers/jfrog/xray/latest/docs/resources/vulnerabilities_report#import)
- [xray_violations_report](https://registry.terraform.io/providers/jfrog/xray/latest/docs/resources/violations_report#import)
- [xray_licenses_report](https://registry.terraform.io/providers/jfrog/xray/latest/docs/resources/licenses_report#import)

**Requirements for and issue**
```
Planning failed. Terraform encountered an error while generating this plan.

│ Error: resource xray_vulnerabilities_report doesn't support import
│
│
```
```
Planning failed. Terraform encountered an error while generating this plan.

│ Error: resource xray_violations_report doesn't support import
│
│
```
```
Planning failed. Terraform encountered an error while generating this plan.

│ Error: resource xray_licenses_report doesn't support import
│
│
```

**Jfrog artifactory version**: 7.77.1
**XRay version:** 3.86.10
**Terraform version:** 1.5.5

**Expected behavior**
Resources should support import.

**Comment by alexhung** [comment]
@neatcoder Thanks for the report. Looks like a bug from first glance. I'll add this to our plan to investigate.

**Comment by alexhung** [comment]
@neatcoder After familiarize myself with this part of the code (haven't touched it in many months), these report resources do not support import. So the documentations are incorrect and I'll be removing the "Import" section.

**Comment by neatcoder** [comment]
Any plans for extending the import support to these resources in future?

**Comment by alexhung** [comment]
@neatcoder Before we can add import support to the provider, the Xray API must support getting all the report generation detail.
