### ISSUE TITLE
Docs 404

### ISSUE THREAD

**Issue by emtunc** [jfrog/terraform-provider-xray#16]
Hey team,
The link in the README points to a dead-end - https://registry.terraform.io/providers/jfrog/xray/latest/docs

**Comment by danielmkn** [comment]
Hi @emtunc, this is because the Xray provider has not been released yet. Once we release the first version, it will appear on the Terraform Registry. Sorry for the inconvenience.

**Comment by emtunc** [comment]
No problem - I saw the deprecation notice when using the xray resource on the main artifactory provider and thought I'd be a good citizen by using this one :D

**Comment by danielmkn** [comment]
That link points to this file: https://github.com/jfrog/terraform-provider-xray/blob/master/docs/index.md
