### ISSUE TITLE
Security filters do not support published date

### ISSUE THREAD

**Issue by neatcoder** [jfrog/terraform-provider-xray#161]
**Describe the bug**
Compared to UI, the security filters in violations report do not support published start/end date

**Requirements for and issue**
![image](https://github.com/jfrog/terraform-provider-xray/assets/28711376/7a817ed9-d475-47fc-ae9a-5c0caef027a0)
V/S
[Provider supported inputs](https://registry.terraform.io/providers/jfrog/xray/latest/docs/resources/violations_report#nested-schema-for-filterssecurity_filters)

**Expected behavior**
UI and TF provider inputs should match

**Comment by alexhung** [comment]
@neatcoder Thanks for the report, I'll add this to our plan to add the date support.
