### ISSUE TITLE
add a data source to fetch xray scan results for an artifact

### ISSUE THREAD

**Issue by matifali** [jfrog/terraform-provider-xray#168]
I want to fetch xray scan results of a docker artifact using the xray provider.

I am proposing having a `data` source with the name `xray_artifact_scan` in the form of,

```tf
data "xray_artifact_scan" "example" {
  artifact = "jfrog.example.com/docker-local/<NAMESPACE>/<IMAGE>:<TAG>"
}

output "image_vulnerabilities" {
  value = data.xray_artifact_scan.example.result
}
```

Here, `data.xray_artifact_scan.example.result` should have the form as returned by the following API endpoint to fetch vulnerabilities in an image. https://jfrog.com/help/r/xray-rest-apis/scans-list-get-artifacts.

```json
{
    "data": [
        {
            "name": "bash_4.3-11+deb8u2_i386.deb",
            "repo_path": "/deb/bash_4.3-11+deb8u2_i386.deb",
            "package_id": "deb://bash",
            "version": "4.3-11+deb8u2",
            "sec_issues": {
                "high": 2,
                "low": 8,
                "medium": 3,
                "total": 13
            },
            "size": "1.13 MB",
            "violations": 0,
            "created": "2022-07-31T12:06:00+03:00",
            "deployed_by": "admin",
            "repo_full_path": "DEBs/deb/bash_4.3-11+deb8u2_i386.deb"
        }
    ],
    "offset": -1
}

```

**Comment by alexhung** [comment]
@matifali Thanks for the suggestion. I've added this to our road map.

**Comment by matifali** [comment]
@alexhung Thanks looking forward to it,

**Comment by matifali** [comment]
Thank you @alexhung. Could you give an example of how it can be used to only get vulnerabilities of a single artifact instead of all the artifacts in the repo?

Thanks :)

**Comment by alexhung** [comment]
@matifali For your use case, you should be able to find the artifact scan using the `repo` and `repo_path` attributes:

```terraform
data "xray_artifacts_scan" "my_artifacts_scan" {
  repo = "docker-local"
  repo_path = "<NAMESPACE>/<IMAGE>:<TAG>"
}
```

**Comment by matifali** [comment]
Great thank you @alexhung
