### ISSUE TITLE
make install broken

### ISSUE THREAD

**Issue by codebop** [jfrog/terraform-provider-xray#19]
make install is currently broken. It errors with the following output:
`sed: 1: "sample.tf": unterminated substitute pattern`

I'm not super knowledgable about sed, but I was able to get make install to work successfully by changing [this line](https://github.com/jfrog/terraform-provider-xray/blob/b0b091bd9a3c9c73ebe070fdf40cfd6679bbe237/GNUmakefile#L18) to use `sed -ie` instead of just `sed -i`

**Comment by danielmkn** [comment]
do you have POSIX sed (Mac default)? It works on GNU sed.

**Comment by codebop** [comment]
Yes I have the mac default sed.

**Comment by danielmkn** [comment]
@codebop , I just checked - `-ie` works on both sed versions. So, I'm gonna add it now.

**Comment by codebop** [comment]
@danielmkn Thanks so much!
