### ISSUE TITLE
licenses endpoint 400 response

### ISSUE THREAD

**Issue by codebop** [jfrog/terraform-provider-xray#22]
I'm a JFrog customer with the following license info: `{
  "type" : "Enterprise",
  "validThrough" : "N/R",
  "licensedTo" : "Artifactory Online Dedicated",
  "subscriptionType" : "enterprise_xray_team"
}`

When I try to use this provider I get the following error: 
`Error: 
400 GET https://opploans.jfrog.io/artifactory/api/system/licenses/
{
  "errors" : [ {
    "status" : 400,
    "message" : "Artifactory Online does not require license, Please contact support@jfrog.com for further assistance if required."
  } ]
}`

If I change https://github.com/jfrog/terraform-provider-xray/blob/94fbbb8fc22d715ffbd744222e7ebfcc9165b5d1/pkg/xray/provider.go#L158 to be `_, err := client.R().SetResult(&license).Get("/artifactory/api/system/license/")` (singular), and re-install the provider it works without error. The JFrog API docs reference "/licenses" not "/license" so I'm not sure if the docs are wrong or what's up with that.

**Comment by danielmkn** [comment]
That's interesting. The documentation for that call is [here](https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-LicenseInformation). 
The singular form is not mentioned there. We will check with the core product team after the weekend and let you know. Thanks!

**Comment by danielmkn** [comment]
SaaS instances have different license API endpoint than On-Prem. And, unfortunately, it's not documented. We will fix it this week.

**Comment by danielmkn** [comment]
Hi @codebop, it's fixed. Also, we've fixed the [documentation](https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-LicenseInformation). Thanks for the contribution!
