### ISSUE TITLE
Add release bundles V2 indexing configuration

### ISSUE THREAD

**Issue by Sam13** [jfrog/terraform-provider-xray#220]
**Is your feature request related to a problem? Please describe.**
Release bundles (V2) indexing configuration cannot be adjusted using this provider.

**Describe the solution you'd like**
Add support for https://jfrog.com/help/r/xray-rest-apis/add-release-bundles-v2-indexing-configuration

**Additional context**
Builds (https://registry.terraform.io/providers/jfrog/xray/latest/docs/resources/binary_manager_builds) and repositories (https://registry.terraform.io/providers/jfrog/xray/latest/docs/resources/binary_manager_repos) are already supported but release bundles are missing:
![image](https://github.com/user-attachments/assets/87ffde87-1b6d-4136-aee3-5be8d38e63b2)

**Comment by alexhung** [comment]
@Sam13 Thanks for the suggestion. I'll add this to our plan.
