### ISSUE TITLE
Patterns do not work with release bundles V2 indexing configuration

### ISSUE THREAD

**Issue by Sam13** [jfrog/terraform-provider-xray#226]
**Describe the bug**
Found while testing the feature https://github.com/jfrog/terraform-provider-xray/issues/220 https://github.com/jfrog/terraform-provider-xray/pull/222

Adding all release bundles (`*/**`) to the indexing configuration does not work.
For builds (https://registry.terraform.io/providers/jfrog/xray/latest/docs/resources/binary_manager_builds) it does.
Error:
```
   │ Error: Provider produced inconsistent result after apply
   │ 
   │ When applying changes to
   │ xray_binary_manager_release_bundles_v2.xray_myproj_indexed_resources_release_bundles_v2,
   │ provider "provider[\"registry.terraform.io/jfrog/xray\"]" produced an
   │ unexpected new value: .indexed_release_bundle_v2: planned set element
   │ cty.StringVal("*/**") does not correlate with any element in actual.
   │ 
   │ This is a bug in the provider, which should be reported in the provider's
   │ own issue tracker.
```

![image](https://github.com/user-attachments/assets/39c8fd80-91e2-49e1-a96f-9138690d0274)

**Requirements for and issue**
- [x] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue)
```
 "xray_binary_manager_builds": {
  "xray_myproj_indexed_resources_builds": {
	"//": {
	  "metadata": {
		"path": "myproj/xray_myproj_indexed_resources_builds",
		"uniqueId": "xray_myproj_indexed_resources_builds"
	  }
	},
	"id": "default",
	"indexed_builds": [
	  "*/**"
	],
	"project_key": "myproj"
  }
},
"xray_binary_manager_release_bundles_v2": {
  "xray_myproj_indexed_resources_release_bundles_v2": {
	"//": {
	  "metadata": {
		"path": "myproj/xray_myproj_indexed_resources_release_bundles_v2",
		"uniqueId": "xray_myproj_indexed_resources_release_bundles_v2"
	  }
	},
	"id": "default",
	"indexed_release_bundle_v2": [
	  "*/**"
	],
	"project_key": "myproj"
  }
}
```

- [x] Your version of Artifactory and Xray (you can `curl` Artifactory version at `$host/artifactory/api/system/version` and Xray version at 
`$host/xray/api/v1/system/version`
```
{"version" : "7.92.1", "revision" : "79201900"}
{"xray_version":"3.101.5","xray_revision":"17f5a9d"}
```

- [x] Your version of terraform
```
Terraform v1.9.3
on linux_amd64

cdktf --version
0.20.8
```
**Expected behavior**
Pattern support for release bundles V2 indexing configuration must be possible

**Additional context**
Import did not recognize patterns as well - it imported an existing release bundle which was not selected

**Comment by alexhung** [comment]
@Sam13 Thanks for the report. The [REST API](https://jfrog.com/help/r/xray-rest-apis/add-release-bundles-v2-indexing-configuration) currently does not support the use of patterns. The POST and PUT APIs will accept `*/**` happily but has no effect. If you set the patterns in the UI, the GET API returns the actual list of release bundles instead.

Until the API supports patterns, you will need to specify the release bundle names in the list.

**Comment by Sam13** [comment]
@alexhung
How does the web UI configure the system?
According my knowledge from the JFrog academy the UI only uses the REST APIs to configure the system.
Are there any plans to add pattern support to the API?

**Comment by alexhung** [comment]
@Sam13 The web UI uses its own set of private/UI only APIs.
