### ISSUE TITLE
Security policy prioritiy ordering fails when "Malicious Packages" type rule has higher priority than "Vulnerability" type rule.

### ISSUE THREAD

**Issue by EitanJoseph** [jfrog/terraform-provider-xray#265]
**Describe the bug**
Terraform: 1.9.8
Artifactory: 7.59.9
Xray: 3.74.8

Providers:
jfrog/xray version: 2.13.0
jfrog/artifactory version: 12.3.2

When creating a security policy, the provider fails when there is a "Malicious Packages" type rule with higher priority than a "Vulnerability" type rule for the same policy. See the example below:

```Terraform
resource "xray_security_policy" "security_review" {
  name        = "security-policy"
  description = "Security policy description"
  type        = "security"

  rule {
    name     = "malicious_packages"
    priority = 1

    criteria {
      malicious_package = true
    }

    actions {
      webhooks                           = ["AdoWebhookTest"]
      block_release_bundle_distribution  = false
      block_release_bundle_promotion     = false
      fail_build                         = false
      notify_watch_recipients            = false
      notify_deployer                    = false
      create_ticket_enabled              = false 
      build_failure_grace_period_in_days = 0     

      block_download {
        unscanned = false
        active    = true
      }
    }
  }

  rule {
    name     = "any_high_and_critrical"
    priority = 2

    criteria {
      min_severity = "High"
    }

    actions {
      webhooks                           = ["AdoWebhookTest"]
      block_release_bundle_distribution  = false
      block_release_bundle_promotion     = false
      fail_build                         = false
      notify_watch_recipients            = false
      notify_deployer                    = false
      create_ticket_enabled              = false 
      build_failure_grace_period_in_days = 0     

      block_download {
        unscanned = false
        active    = true
      }
    }
  }
}
```

The reason I believe this to be a bug: If you were to swap the priorities, setting the "Vulnerabilities" rule priority 1 and the "Malicious Packages" rule priority 2 then the provider will work. The JFrog UI allows for for either priority ordering and as such the provider should also handle both. 

**Requirements for and issue**
- [x] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue)
- [x] Your version of Artifactory and Xray (you can `curl` Artifactory version at `$host/artifactory/api/system/version` and Xray version at 
`$host/xray/api/v1/system/version`
- [x] Your version of terraform

**Expected behavior**
You should be able to update or create a new policy with any ordering of priorities for rules.

**Additional context**
N/A

**Comment by alexhung** [comment]
@EitanJoseph Thanks for the report! I agree that the ordering shouldn't matter. Let me investigate if this is a API issue.

**Comment by alexhung** [comment]
@EitanJoseph What's the error message (or logs) when the provider fails? Can you share?
