### ISSUE TITLE
Upgrading provider version results in plan run time increase

### ISSUE THREAD

**Issue by nbaju1** [jfrog/terraform-provider-xray#271]
**Describe the bug**
We recently did a refactor of our JFrog IAC where we also bumped the Artifactory provider version from 10.8.3 to ~12.3.0. The refactor was mostly renaming resources for better readability, no new resources were added. 

After the version update the run time for `terraform plan` increased from ~30 seconds to ~8 minutes. Looking at the changes introduced in versions after 10.8.3, the addition of `UpgradeState` function for `artifactory_user` is one of the suspects for the main source of the run time increase. Is the intention to execute this on each `terraform plan` run? 

We have ~1000 internal users (used for service accounts) and from the logs I see that an API call is made for each user which I don't see prior to the update.

As I would rather not be stuck on an outdated version of the provider, is there something we can do to avoid this long run time? 

**Requirements for and issue**
- [x] A description of the bug
- [ ] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue). **If this is not supplied, this issue will likely be closed without any effort expended.** NOT APPLICABLE
- [x] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
- [x] Your version of terraform
- [x] Your version of terraform provider

Terraform 1.9.8
Artifactory provider 12.3.0
Artifactory version: 7.100.2

**Expected behavior**
Hopefully not a 1500% increase in run time for `terraform plan`.

**Comment by alexhung** [comment]
@nbaju1 Interesting. Can you try with Xray provider v2.11.0 and v2.11.1? I want to pin down when this performance issue first occurs. I have my suspicion but would like someone to confirm it 😄

**Comment by alexhung** [comment]
@nbaju1 I wonder if this is related to #262 as well.

**Comment by nbaju1** [comment]
@alexhung 2.11.0 works similar to 2.8.0. 2.11.1 introduces the new expected types mentioned above and results in the aforementioned increase in run time.

**Comment by nbaju1** [comment]
> [@nbaju1](https://github.com/nbaju1) I wonder if this is related to [#262](https://github.com/jfrog/terraform-provider-xray/issues/262) as well.

We have 128 licenses in our allow list.

**Comment by alexhung** [comment]
> [@alexhung](https://github.com/alexhung) 2.11.0 works similar to 2.8.0. 2.11.1 introduces the new expected types mentioned above and results in the increase in run time.

That's what I suspected. The change between 2.11.0 and 2.11.1 should be transparent to end users. The attribute types should be compatible between versions.

Let me take a deeper look into this.

**Comment by alexhung** [comment]
@nbaju1 See [my comment in the other thread](https://github.com/jfrog/terraform-provider-xray/issues/262#issuecomment-2480018643) and [this GitHub issue](https://github.com/hashicorp/terraform/issues/32940).

**Comment by alexhung** [comment]
@nbaju1 See [my comment](https://github.com/jfrog/terraform-provider-xray/issues/262#issuecomment-2483940372). If you have opinion on which approach works for you, please let me know. I suspect switching attribute type will help your use case.

**Comment by nbaju1** [comment]
@alexhung, thanks for the update. I believe changing attribute type will work for us. Since we use the CDK, adding our own validation is relatively simple, so the loss of that functionality is not that important.
