### ISSUE TITLE
xray_webhook provider existing headers not recognized during plan step

### ISSUE THREAD

**Issue by EitanJoseph** [jfrog/terraform-provider-xray#290]
**Describe the bug**
Terraform: 1.9.8
Artifactory: 7.59.9
Xray: 3.74.8

Providers:
jfrog/xray version: 3.0.2
jfrog/artifactory version: 12.3.2

The xray_webhook provider offers the `headers` field however this field is not properly analyzed by the terraform plan step. In particular, when you initialize terraform and import your existing xray webhook, the terraform plan step incorrectly claims that changes will be made to the headers field of your xray_webhook resource.

To recreate this issue create an xray webhook  with headers (in my case specifically Authorization) and import the resource to a terraform configuration that is an exact match. 

```
resource "xray_webhook" "xray_webhook" {
    name = "AdoWebhook"
    url = "url"
    use_proxy = true
    description =  "Description"
    headers = { Authorization = "Basic auth_token" }
}
```

Then run `terraform plan` and see that there is a claim of headers requiring an update.

Additionally, if you apply your terraform configuration, **then re-initialize and re-import the resource**, then run `terraform plan`, you will once again see the claim that the webhook's headers are going to be "added (+)" 

**Requirements for and issue**
- [x] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue)
- [x] Your version of Artifactory and Xray (you can `curl` Artifactory version at `$host/artifactory/api/system/version` and Xray version at 
`$host/xray/api/v1/system/version`
- [x] Your version of terraform

**Expected behavior**
I expect that when I terraform plan an xray_webhook configuration that is a 1 to 1 match with the real configuration that terraform does not report a (+) change.

**Additional context**
Only tried this with the header `Authorization` and `terraform plan` seems to work correctly right after you apply your changed but don't re-import the resource.

**Comment by alexhung** [comment]
@EitanJoseph Thanks for the report! I've added this to our plan to investigate and fix.
