### ISSUE TITLE
Add resource/data for DB Sync Daily Update Time 

### ISSUE THREAD

**Issue by bmanuel** [jfrog/terraform-provider-xray#34]
**Is your feature request related to a problem? Please describe.**
Our DB usage spikes during the sync and it causes alerts to be produced for the database.

**Describe the solution you'd like**
I would like to be able to set the sync time to a lower utilization time. I would also like to be able to query the sync time in order to set up expected maintenance periods in our alerting using terraform.

**Describe alternatives you've considered**
Manually setting the sync time via the API and hard coding it as needed in terraform.

**Additional context**
https://www.jfrog.com/confluence/display/JFROG/Xray+REST+API#XrayRESTAPI-UpdateDBSyncDailyUpdateTime

**Comment by danielmkn** [comment]
@bmanuel, implemented in v1.0.0
