### ISSUE TITLE
Add Xray Compliance License Resource

### ISSUE THREAD

**Issue by briandbecker** [jfrog/terraform-provider-xray#38]
**Is your feature request related to a problem? Please describe.**
As a security person, I would like to use Terraform to describe my entire xray configuration.  The provider doesn't support the ability to create custom compliance licenses which need to be defined prior to creating my license policies ( it doesn't appear the API is documented either)

**Describe the solution you'd like**
Add a resource for xray compliance license in order to create the license prior to creating the policy.

**Describe alternatives you've considered**
None - as the api isn't even documented using other terraform provider to call the raw api doesn't seem viable.

**Additional context**
None

**Comment by chb0github** [comment]
@briandbecker do you create it through the UI?

**Comment by danielmkn** [comment]
Unfortunately, we can't implement this at the moment, because of the absence of a public API for managing Custom Compliance Licenses. An internal ticket was created for the Xray team to add API support.
