### ISSUE TITLE
Support configuring reports 

### ISSUE THREAD

**Issue by asvoboda** [jfrog/terraform-provider-xray#60]
Currently, the xray tf provider does not support configuring reports. The API [1] supports creating various types of reports with many options. Ideally, support should exist in this provider for the following set of distinct report types

- [ ] vulnerabilities
- [ ] licenses
- [ ] violations
- [ ] operational risks

[1] https://www.jfrog.com/confluence/display/JFROG/Xray+REST+API#XrayRESTAPI-REPORTS

**Comment by chb0github** [comment]
Ok, well, let me knock the ball back into your court.

Our documentation isn't the best, and after looking at it I am pondering if it can meet the terraform lifecycle; meaning I'd have to research it's feasibility. 

But, before I go that far, how about you propose some hcl that

- Creates a report
- Reads a report
- updates a report
- deletes a report

**Comment by danielmkn** [comment]
@asvoboda, it's released in v1.9.0, thanks for the ticket!
