### ISSUE TITLE
Add support for Xray Ignore Rules

### ISSUE THREAD

**Issue by spuder** [jfrog/terraform-provider-xray#67]
Xray does container scanning, and supports `Ignore rules` for allowing exceptions. 

We have many containers that are reporting critical vulerabilities that are not actually critical due to other compensating controls we have in place. 

We want the ability to programatically define `ignore rules` using terraform as infrastructure as code

[Documentation](https://www.jfrog.com/confluence/display/JFROG/Ignore+Rules)  
[Rest API Documentation](https://www.jfrog.com/confluence/display/JFROG/Xray+REST+API#XrayRESTAPI-IGNORERULES)

```
POST /api/v1/ignore_rules
“vulnerabilities”/“licenses”/“cves”/“policies”/“watches”/“docker-layers”  - []string 
```

**Comment by chb0github** [comment]
Please offer up some potential HCL you'd like to see

**Comment by spuder** [comment]
# proposal 1

https://www.jfrog.com/confluence/display/JFROG/Ignore+Rules#IgnoreRules-IgnoringViolationsExamples

```
resource "artifactory_vulerability_ignore_rule" {
  note = "approved by CISO"
  expiration_time = "2020-12-24"
  vulnerability = "any"
  component = {
    version= 2.1.5,
     url = "gav://com.atlassian.maven.pulings" 
  }
  artifact = "generic://sha256:123456"
}
```

![image](https://user-images.githubusercontent.com/242382/177871294-fcce2be0-beb4-4b57-955b-e79cbd053363.png)

**Comment by oallauddin** [comment]
When this is implemented please add an attribute for the optional projectKey query parameter. 
So we can ignore_rules for a watch that is tied to a project.
`POST /api/v1/ignore_rules?projectKey=test`
