### ISSUE TITLE
Support for XRAY webhooks

### ISSUE THREAD

**Issue by chb0github** [jfrog/terraform-provider-xray#7]
**Is your feature request related to a problem? Please describe.**
Not related to a problem. However, the ability to create webhooks in xray is important for other integrations

**Describe the solution you'd like**
```hcl
resource "xray_webhook" "myotherservice" {
   url = "http://thing.com/hook"
   auth { // xor on these 3 methods
    bearer { // optional
       token = "marked as sensitive"
    }
    basic {
      username = "optional"
      password = "sensitive"
    }
    header {
     FooHeader = "sensitive"
     }
   }
   headers {
    MyHeader = "value"
   }
}
```

**Additional context**
There is no current "legit" api for this, so the UI endpoint will need to be used. Please talk to @alexhung or Karol where to find an example integration

**Comment by danielmkn** [comment]
We've decided not to use private APIs in the TF providers. The internal ticket to add public API was submitted to the Xray team.
