### ISSUE TITLE
Indexed Resources in terraform

### ISSUE THREAD

**Issue by mor-benhamo** [jfrog/terraform-provider-xray#70]
Hey, please add the ability to add repositories to "Indexed Resources" in Xray. this will allow us to manage multiple clusters \ regions in a single location.

**Comment by alexhung** [comment]
@mor-benhamo Are you referring to the setting in the repository to enable Xray indexing?
![Screen Shot 2022-07-21 at 3 45 46 PM](https://user-images.githubusercontent.com/27263/180327530-9c261255-018c-4c4d-a2ac-b6b9f0a4abe6.png)

This is already supported in the [Artifactory provider](https://github.com/jfrog/terraform-provider-artifactory).

**Comment by alexhung** [comment]
@mor-benhamo I think you're referring to this page in Xray?
![Screen Shot 2022-07-21 at 3 48 14 PM](https://user-images.githubusercontent.com/27263/180327908-892834db-1a73-4c56-987f-fe3488c3f07d.png)

This shows the repositories that have been indexed by Xray and is controlled by the setting in Artifactory provider's `xray_index` attribute.

**Comment by mor-benhamo** [comment]
I believe so. thanks. ill try the flag "xray_index"
