### ISSUE TITLE
Add support for repository retention policies

### ISSUE THREAD

**Issue by jamestoyer** [jfrog/terraform-provider-xray#77]
In Xray v3.41.4 support for [retention periods for scans](https://www.jfrog.com/confluence/display/JFROG/Indexing+Xray+Resources#IndexingXrayResources-SetaRetentionPeriod) was added. This allows for configuration of the number of days scans should be kept for, as well as being able to set retention periods based on specific ant patterns. The latter is useful for removing source jars from maven scans. 

The Xray API supports this [1][2] and a resource (or resources) for this should be added to the Xray provider to support this. 

[1] https://www.jfrog.com/confluence/display/JFROG/Xray+REST+API#XrayRESTAPI-UpdateRepositoriesConfigurations
[2] https://www.jfrog.com/confluence/display/JFROG/Xray+REST+API#XrayRESTAPI-GetRepositoriesConfigurations

**Comment by alexhung** [comment]
@jamestoyer Thanks for the request. We'll add this to our schedule.

**Comment by danielmkn** [comment]
@jamestoyer, it's released in v1.7.0, thanks for the ticket!
