### ISSUE TITLE
documentation says operational risk policy type is Operational_Risk

### ISSUE THREAD

**Issue by RobertBlumen** [jfrog/terraform-provider-xray#96]
**Describe the bug**
[terraform documentation](https://registry.terraform.io/providers/jfrog/xray/latest/docs/resources/operational_risk_policy) says that the type field for xray_operational_risk_policy should have value "Operational_Risk".  This causes a failure with an invalid policy error.  The correct value is "operational_risk"

**Requirements for and issue**
- use the code sample in the terraform documentation
- artifactory version: 7.417
- xray version: 3.60.2
- terraform 1.1.3

**Expected behavior**

**Additional context**

**Comment by alexhung** [comment]
@RobertBlumen Thank you for the report. When the policy for operational risk was implemented original, the type required by Xray API was `Operational_Risk`. Since then it must have been fixed by the Xray team to lowercase. We'll update the provider to match.

**Comment by danielmkn** [comment]
Thanks! It will be fixed this week!

**Comment by danielmkn** [comment]
Released in v1.9.6
