### ISSUE TITLE
error message for incorrect policy type is not helpful

### ISSUE THREAD

**Issue by RobertBlumen** [jfrog/terraform-provider-xray#97]
**Describe the bug**
- when the xray_operational_risk_policy field `type` is set to the value `"Operational_Risk"` the error message is `"Got Invalid Policy"`.  The error message should provide more information about why the policy is invalid. 

**Requirements for and issue**

```
resource "xray_operational_risk_policy" "op_risk" {
  name        = "operational-risk"
  description = "operational risk policy"
  type        = "Operational_Risk"  # terraform documentation says "Operational_Risk", which is wrong

  rule {
    name     = "the-rule"
    priority = 1

    criteria {
      op_risk_min_risk = "Medium"
    }

    actions {
      webhooks                          = []
      mails                             = []
      block_release_bundle_distribution = false
      fail_build                        = false
      notify_watch_recipients           = false
      notify_deployer                   = false
      create_ticket_enabled             = false

      block_download {
        unscanned = false
        active    = false
      }
    }
  }
}
```

- artifactory version: 7.417
- xray version: 3.60.2
- terraform 1.1.3

**Expected behavior**
- the error message should be "The value Operational_Risk is not a valid policy type.  Did you mean operational_risk?"

**Additional context**
```
 Error: 
│ 400 PUT https://artifactory.katanagraph.io/xray/api/v2/policies/operational-risk
│ {"error":"Got Invalid Policy 'operational-risk'"}
```

**Comment by danielmkn** [comment]
Hi @RobertBlumen! Thanks for the ticket. This error message is coming from the API response and we can't fix it in the provider. I'll ask the Xray team if they can clarify the error message.
